---
- name: Install letsencrypt
  apt: name=letsencrypt state=latest update_cache=yes

- apt_repository:
    repo: 'ppa:certbot/certbot'

- name: Check ssl keyfile
  stat:
          path: /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem
  register: stat_result

- name: Install base conf for ssl
  template: src=base-syberiayoubear.devops.srwx.net.conf.j2 dest=/etc/nginx/sites-enabled/syberiayoubear.devops.srwx.net.conf owner=root group=root mode=0644
  when: stat_result.stat.exists == False
  register: checkpoint

- name: restart nginx if base conf was upload
  service: name=nginx state=restarted
  when: checkpoint.changed

- name: check directory for certbot
  file: name=/etc/letsencrypt state=directory

- name: upload certbot conf
  template: src=cli.ini dest=/etc/letsencrypt/cli.ini owner=root group=root mode=0644

- name: check 2nd directory for certbot
  file: name=/var/www/html/.well-known/acme-challenge state=directory

- name: create letsencrypt certificate
  shell: letsencrypt certonly --non-interactive --agree-tos --webroot -w /var/www/html -d {{ domain_name }} --email {{ letsencrypt_email }}
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem
  notify: restart nginx

- cron:
    name: certbot
    minute: "30"
    hour: "*/12"
    job: "certbot renew --quiet --allow-subset-of-names"
